### ISSUE TITLE
Proposition de documentation

### ISSUE THREAD

**Issue by pentux-GitHub** [fathzer/JClop#1]
Bonjour,

   je vous propose une base pour la documentation Jclop.

   Merci de me dire si cela vous est utile.

   Bonne réception, Pentux.

[JClop_Initial_Detailed_Documentation_EN.md](https://github.com/jclop2/JClop/files/12566236/JClop_Initial_Detailed_Documentation_EN.md)

**Comment by fathzer** [comment]
Bonjour,
J'ai ajouté de la documentation dans le README de ce projet, ainsi que dans celui de l'implémentation [Dropbox](https://github.com/jclop2/dropbox),
Cordialement,
Jean-Marc Astesana
PS : Ce n'est pas précisé dans la doc, mais ces librairies ne sont pas conçues pour Android; La synchronisation est synchrone. Donc en cas de coupure réseau, on obtient une exception. Il faut alors resynchroniser la totalité du fichier (pas de reprise du point où il y a eu la coupure). [Dropbox propose une librairie](https://www.dropbox.com/developers/documentation?_tk=pilot_lp&_ad=topbar1&_camp=docs) qui, peut-être, est plus adaptée.
